### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by mballaro** [ocean-data-challenges/2021a_SSH_mapping_OSE#1]
- [x] Put the along-track data & the various gridded SSH reconstructions on AVISO+ server
- [x] Update notebooks with correct file links
- [x] Update README
- [x] Make DEMO Quickstart with: reading some along-track, baseline mapping over few month and validation with independent dataset
- [ ] Add test case with DUACS-DT2021 OI parameters
- [x] Update requirements.txt
- [x] Put correct DOI
- [x] Add archive to zenodo + get DOI
- [x] Add binder demo
- [x] Handbook AVISO+
- [x] Test AVISO+ data accessibility when not connected to CLS network
- [x] webpage AVISO+
- [x] Add info for managing env: conda env create -f environment.yml
- [ ] Overall review
